version: '3.9'

services:
  # On garde le service web configuré au cas où, mais on ne le lancera pas

  db:
    image: postgres:15
    # --- AJOUT IMPORTANT ICI ---
    # Cela permet à ton 'python manage.py runserver' local de parler au Docker
    ports:
      - "5433:5432"  
    # ---------------------------
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env

volumes:
  postgres_data: