# Generated by Django 6.0 on 2026-01-17 15:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module_expert', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apprenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apprenant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilEtudiant',
            fields=[
                ('apprenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profil', serialize=False, to='module_apprenant.apprenant')),
                ('xp_total', models.PositiveIntegerField(default=0)),
                ('lacunes_identifiees', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badges', models.ManyToManyField(blank=True, to='module_apprenant.badge')),
            ],
        ),
        migrations.CreateModel(
            name='NiveauCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_actuel', models.CharField(choices=[('DEBUTANT', 'Débutant'), ('INTERMEDIAIRE', 'Intermédiaire'), ('AVANCE', 'Avancé'), ('EXPERT', 'Expert')], default='DEBUTANT', max_length=20)),
                ('score_anamnese', models.FloatField(default=0.0)),
                ('score_diagnostic', models.FloatField(default=0.0)),
                ('score_traitement', models.FloatField(default=0.0)),
                ('score_relationnel', models.FloatField(default=0.0)),
                ('progression_globale', models.FloatField(default=0.0)),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='niveaux_apprenants', to='module_expert.domainemedical')),
                ('profil_etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='module_apprenant.profiletudiant')),
            ],
            options={
                'unique_together': {('profil_etudiant', 'domaine')},
            },
        ),
    ]
