# Generated by Django 6.0 on 2025-12-10 15:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module_expert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apprenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfilEtudiant',
            fields=[
                ('apprenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='module_apprenant.apprenant')),
                ('xp_total', models.PositiveIntegerField(default=0)),
                ('lacunes_identifiees', models.TextField(blank=True)),
                ('badges', models.ManyToManyField(blank=True, to='module_apprenant.badge')),
            ],
        ),
        migrations.CreateModel(
            name='NiveauCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_actuel', models.CharField(choices=[('DEBUTANT', 'Débutant'), ('INTERMEDIAIRE', 'Intermédiaire'), ('AVANCE', 'Avancé'), ('EXPERT', 'Expert')], max_length=20)),
                ('score_diagnostic', models.FloatField(default=0.0)),
                ('score_raisonnement', models.FloatField(default=0.0)),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='niveaux_apprenants', to='module_expert.domainemedical')),
                ('profil_etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='module_apprenant.profiletudiant')),
            ],
            options={
                'unique_together': {('profil_etudiant', 'domaine')},
            },
        ),
    ]
