# Generated by Django 6.0 on 2026-01-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_apprenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionProfiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence', models.CharField(max_length=100)),
                ('situation', models.TextField()),
                ('question_text', models.TextField()),
                ('options', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='profiletudiant',
            name='est_profile',
            field=models.BooleanField(default=False),
        ),
    ]
