# Generated by Django 6.0 on 2026-01-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_apprenant', '0002_questionprofiling_profiletudiant_est_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletudiant',
            name='global_anamnese',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profiletudiant',
            name='global_diagnostic',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profiletudiant',
            name='global_relationnel',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profiletudiant',
            name='global_traitement',
            field=models.FloatField(default=0.0),
        ),
    ]
