# Generated by Django 6.0 on 2025-12-10 15:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module_apprenant', '0001_initial'),
        ('module_expert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionApprentissage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('score_session', models.IntegerField(default=0, null=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='module_apprenant.apprenant')),
                ('cas_clinique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='module_expert.casclinique')),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question_contenu', models.TextField()),
                ('reponse_contenu', models.TextField(blank=True)),
                ('reponse_est_valide', models.BooleanField(null=True)),
                ('feedback_contenu', models.TextField(blank=True)),
                ('feedback_type', models.CharField(blank=True, choices=[('DIRECT', 'Direct'), ('SOCRATIQUE', 'Socratique'), ('SCAFFOLDING', 'Scaffolding')], max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='module_interface.sessionapprentissage')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
