# Generated by Django 6.0 on 2026-01-18 19:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_interface', '0002_persistentsession_sessionevent_sessionmemory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationSommative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_global', models.IntegerField()),
                ('score_diagnostic', models.IntegerField()),
                ('score_anamnese', models.IntegerField()),
                ('score_prise_en_charge', models.IntegerField()),
                ('score_communication', models.IntegerField()),
                ('difficultes_identifiees', models.JSONField(default=list)),
                ('points_forts', models.JSONField(default=list)),
                ('feedback_global', models.TextField()),
                ('date_evaluation', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='module_interface.sessionapprentissage')),
            ],
        ),
    ]
