# Generated by Django 6.0 on 2026-01-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_interface', '0003_evaluationsommative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persistentsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sessionevent',
            name='session',
        ),
        migrations.DeleteModel(
            name='SessionMemory',
        ),
        migrations.DeleteModel(
            name='PersistentSession',
        ),
        migrations.DeleteModel(
            name='SessionEvent',
        ),
    ]
