# Generated by Django 6.0 on 2025-12-10 15:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomaineMedical',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CasClinique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('BROUILLON_IA', 'Brouillon (IA)'), ('EN_REVISION', 'En Révision'), ('PUBLIE', 'Publié'), ('REJETE', 'Rejeté'), ('ARCHIVE', 'Archivé')], default='BROUILLON_IA', max_length=20)),
                ('difficulte', models.CharField(choices=[('DEBUTANT', 'Débutant'), ('INTERMEDIAIRE', 'Intermédiaire'), ('AVANCE', 'Avancé'), ('EXPERT', 'Expert')], max_length=20)),
                ('donnees_patient', models.JSONField()),
                ('historique_medical', models.TextField()),
                ('solution_experte', models.TextField()),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('source_fultang_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cas_cliniques', to='module_expert.domainemedical')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertHumain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('matricule', models.CharField(max_length=100, unique=True)),
                ('domaine_expertise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experts_humains', to='module_expert.domainemedical')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertIA',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nom_ia', models.CharField(max_length=255)),
                ('base_connaissance', models.TextField(blank=True)),
                ('domaine_specialisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experts_ia', to='module_expert.domainemedical')),
            ],
        ),
        migrations.CreateModel(
            name='EtapeClinique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('type_etape', models.CharField(blank=True, max_length=100)),
                ('cas_clinique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='module_expert.casclinique')),
            ],
            options={
                'ordering': ['ordre'],
                'unique_together': {('cas_clinique', 'ordre')},
            },
        ),
    ]
