# Generated by Django 6.0 on 2026-01-17 13:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomaineMedical',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CasClinique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_unique', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('titre', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('BROUILLON_IA', 'Brouillon (IA)'), ('EN_REVISION', 'En Révision'), ('PUBLIE', 'Publié'), ('REJETE', 'Rejeté'), ('ARCHIVE', 'Archivé')], default='BROUILLON_IA', max_length=20)),
                ('difficulte', models.CharField(choices=[('DEBUTANT', 'Débutant'), ('INTERMEDIAIRE', 'Intermédiaire'), ('AVANCE', 'Avancé'), ('EXPERT', 'Expert')], max_length=20)),
                ('pathologie', models.CharField(blank=True, max_length=255)),
                ('donnees_patient', models.JSONField(help_text='Données personnelles: age, sexe, profession...')),
                ('motif_consultation', models.TextField(blank=True)),
                ('mode_de_vie', models.JSONField(blank=True, default=dict)),
                ('antecedents_medicaux', models.JSONField(blank=True, default=dict)),
                ('symptomes', models.JSONField(blank=True, default=list)),
                ('diagnostics_physiques', models.JSONField(blank=True, default=list)),
                ('examens_complementaires', models.JSONField(blank=True, default=list)),
                ('diagnostic_final', models.CharField(blank=True, max_length=255)),
                ('traitement', models.JSONField(blank=True, default=list)),
                ('objectifs_pedagogiques', models.JSONField(blank=True, default=list)),
                ('indices_cliniques', models.JSONField(blank=True, default=list)),
                ('erreurs_courantes', models.JSONField(blank=True, default=list)),
                ('solution_experte', models.TextField(blank=True, help_text='Résumé global de la solution')),
                ('historique_medical', models.TextField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('source_fultang_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cas_cliniques', to='module_expert.domainemedical')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertHumain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(default='default@email.com', max_length=254, unique=True)),
                ('matricule', models.CharField(max_length=100, unique=True)),
                ('domaine_expertise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experts_humains', to='module_expert.domainemedical')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='experthumain', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpertIA',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nom_ia', models.CharField(max_length=255)),
                ('base_connaissance', models.TextField(blank=True)),
                ('domaine_specialisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experts_ia', to='module_expert.domainemedical')),
            ],
        ),
        migrations.CreateModel(
            name='EtapeClinique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('type_etape', models.CharField(blank=True, max_length=100)),
                ('cas_clinique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='module_expert.casclinique')),
            ],
            options={
                'ordering': ['ordre'],
                'unique_together': {('cas_clinique', 'ordre')},
            },
        ),
    ]
