# Generated by Django 4.2.27 on 2026-01-19 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_expert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casclinique',
            name='commentaire_expert',
            field=models.TextField(blank=True, help_text="Commentaire de l'expert"),
        ),
        migrations.AddField(
            model_name='casclinique',
            name='date_mise_en_cours',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casclinique',
            name='email_notification_rejet',
            field=models.EmailField(blank=True, help_text='Email pour notification de rejet (Fultang)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='casclinique',
            name='expert_responsable',
            field=models.ForeignKey(blank=True, help_text='Expert responsable du cas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cas_assignes', to='module_expert.experthumain'),
        ),
        migrations.AddField(
            model_name='casclinique',
            name='parties_concernees',
            field=models.JSONField(blank=True, default=list, help_text='Parties du cas concernées par le rejet'),
        ),
        migrations.AddField(
            model_name='casclinique',
            name='raison_rejet',
            field=models.TextField(blank=True, help_text='Raison détaillée du rejet'),
        ),
        migrations.AlterField(
            model_name='casclinique',
            name='statut',
            field=models.CharField(choices=[('BROUILLON_IA', 'Brouillon (IA)'), ('EN_REVISION', 'En Révision'), ('EN_COURS', 'En Cours'), ('PUBLIE', 'Publié'), ('REJETE', 'Rejeté'), ('ARCHIVE', 'Archivé')], default='BROUILLON_IA', max_length=20),
        ),
    ]
